export const mockPoliticians = [
    {
      id: "1",
      fullName: "Jane Smith",
      title: "Rt Hon",
      constituency: "London North",
      party: "Labour",
      yearlyPassiveIncome: 125000,
      wealthTaxContribution: 45000,
      photoUrl: "/placeholder.svg?height=400&width=400",
    },
    {
      id: "2",
      fullName: "John Brown",
      title: "Sir",
      constituency: "Manchester South",
      party: "Conservative",
      yearlyPassiveIncome: 210000,
      wealthTaxContribution: 75000,
      photoUrl: "/placeholder.svg?height=400&width=400",
    },
    {
      id: "3",
      fullName: "Sarah Johnson",
      title: "",
      constituency: "Edinburgh East",
      party: "SNP",
      yearlyPassiveIncome: 95000,
      wealthTaxContribution: 32000,
      photoUrl: "/placeholder.svg?height=400&width=400",
    },
    {
      id: "4",
      fullName: "Michael Wilson",
      title: "Dr",
      constituency: "Cardiff Central",
      party: "Liberal Democrats",
      yearlyPassiveIncome: 150000,
      wealthTaxContribution: 50000,
      photoUrl: "/placeholder.svg?height=400&width=400",
    },
    {
      id: "5",
      fullName: "Elizabeth Taylor",
      title: "",
      constituency: "Belfast West",
      party: "Green",
      yearlyPassiveIncome: 85000,
      wealthTaxContribution: 28000,
      photoUrl: "/placeholder.svg?height=400&width=400",
    },
    {
      id: "6",
      fullName: "Robert Davis",
      title: "Rt Hon",
      constituency: "Birmingham North",
      party: "Conservative",
      yearlyPassiveIncome: 175000,
      wealthTaxContribution: 60000,
      photoUrl: "/placeholder.svg?height=400&width=400",
    },
  ]
  